### ISSUE TITLE
上传可以成功,但是不能够查看历史

### ISSUE THREAD

**Issue by caidwang** [fate-lovely/pic-on-qiniu#3]
上传可以成功,并且外链可以使用, 但是查看历史的时候一直是"正在从七牛获取数据的界面"
使用的是71.0.3578.98（正式版本） （64 位）的chrome

**Comment by fate-lovely** [comment]
@caidwang 问题修复了，很愚蠢的问题 😂，我已经更新到了 Chrome 商店，从 Github 仓库直接下载安装也可以的。
