### ISSUE TITLE
希望增加上传成功直接复制到剪贴板的功能

### ISSUE THREAD

**Issue by zj1123581321** [fate-lovely/pic-on-qiniu#5]
新浪图床倒下了，估计利用其他插件的图床工具会有一个较多的用户增长。

如果这款工具可以像[微博图床](https://chrome.google.com/webstore/detail/%E5%BE%AE%E5%8D%9A%E5%9B%BE%E5%BA%8A/pinjkilghdfhnkibhcangnpmcpdpmehk?utm_source=chrome-ntp-icon)一样支持直接复制到剪贴板地址，就极为方便了。

**Comment by fate-lovely** [comment]
@zj1123581321 新浪图床我刚刚试了，可以的。然后，我这边设计的是点击会复制到剪切板，多了一个步骤，友好一点。
